### ISSUE TITLE
The key with alias metadata has been changed, re-instate the previous keystore

### ISSUE THREAD

**Issue by lmeunier** [Alfresco/alfresco-ssl-generator#10]
Hello,

I'm trying to add mutual TLS authentication to an already existing ACS 6.2 / ASS 1.3 installation.

Keystores and truststores have been generated using the alfresco-ssl-generator tool:
```
PASSWORD="myverysecretpassword"

git clone https://github.com/Alfresco/alfresco-ssl-generator
cd alfresco-ssl-generator/ssl-tool
./run.sh -alfrescoversion enterprise \
         -keysize 1024 \
         -keystoretype JCEKS \                                                                                 
         -truststoretype JCEKS \
         -keystorepass "$PASSWORD" \
         -truststorepass "$PASSWORD" \
         -encstorepass "$PASSWORD" \
         -encmetadatapass "$PASSWORD"\
         -cacertdname "/C=FR/ST=France/L=France/O=FOO/OU=BAR/CN=FOOBAR-ca" \
         -repocertdname "/C=FR/ST=France/L=France/O=FOO/OU=BAR/CN=FOOBAR-acs-repo" \
         -solrcertdname "/C=FR/ST=France/L=France/O=FOO/OU=BAR/CN=FOOBAR-acs-repo-client" \
         -browsercertdname "/C=FR/ST=France/L=France/O=FOO/OU=BAR/CN=FOOBAR-browser-client" \
         -caservername localhost \
         -alfrescoservername localhost \
         -solrservername localhost \
         -alfrescoformat classic
```

ACS and ASS have been configured as described on this page https://docs.alfresco.com/search-services/latest/install/options/#install-with-mutual-tls-zip

Solr starts without error and I've access to the Solr web UI using the browser certificate.
But ACS throws an error during the startup:

```
2021-03-02 10:14:13,673  ERROR [web.context.ContextLoader] [localhost-startStop-1] Context initialization failed
org.alfresco.error.AlfrescoRuntimeException: 02020000 Keystores are invalid
	at org.alfresco.encryption.EncryptionChecker$1.execute(EncryptionChecker.java:78)
	at org.alfresco.encryption.EncryptionChecker$1.execute(EncryptionChecker.java:1)
	at org.alfresco.repo.transaction.RetryingTransactionHelper.doInTransaction(RetryingTransactionHelper.java:450)
	at org.alfresco.repo.transaction.RetryingTransactionHelper.doInTransaction(RetryingTransactionHelper.java:319)
	at org.alfresco.encryption.EncryptionChecker.onBootstrap(EncryptionChecker.java:67)
	at org.springframework.extensions.surf.util.AbstractLifecycleBean.onApplicationEvent(AbstractLifecycleBean.java:56)
	at org.alfresco.repo.management.SafeApplicationEventMulticaster.multicastEventInternal(SafeApplicationEventMulticaster.java:221)
	at org.alfresco.repo.management.SafeApplicationEventMulticaster.multicastEvent(SafeApplicationEventMulticaster.java:186)
	at org.alfresco.repo.management.SafeApplicationEventMulticaster.multicastEvent(SafeApplicationEventMulticaster.java:206)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:402)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:359)
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:896)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:552)
	at org.springframework.web.context.ContextLoader.configureAndRefreshWebApplicationContext(ContextLoader.java:401)
	at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:292)
	at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:103)
	at org.alfresco.web.app.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:70)
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4699)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5165)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:743)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:719)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:714)
	at org.apache.catalina.startup.HostConfig.deployDescriptor(HostConfig.java:614)
	at org.apache.catalina.startup.HostConfig$DeployDescriptor.run(HostConfig.java:1823)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.alfresco.encryption.InvalidKeystoreException: The key with alias metadata has been changed, re-instate the previous keystore
	at org.alfresco.encryption.AlfrescoKeyStoreImpl.validateKeys(AlfrescoKeyStoreImpl.java:922)
	at org.alfresco.encryption.AlfrescoKeyStoreImpl.validateKeys(AlfrescoKeyStoreImpl.java:188)
	at org.alfresco.encryption.KeyStoreChecker.validateKeyStores(KeyStoreChecker.java:49)
	at org.alfresco.encryption.EncryptionChecker$1.execute(EncryptionChecker.java:73)
	... 29 more
Mar 02, 2021 10:14:13 AM org.apache.catalina.core.StandardContext listenerStart
```

**Comment by aborroy** [comment]
You need to keep your `keystore` file and `keystore-passwords.properties` from your previous environment. This files are associated with Alfresco Repository and they are not related with mTLS but with Alfresco Repository encryption.

Discard the `keystore` and `keystore-passwords.properties` files generated by this project in `alfresco` folder and replace them by the existing in your previous environment.

**Comment by lmeunier** [comment]
Thank you. ACS has started after replacing the `keystore` and `keystore-passwords.properties` files with the already existing ones.

**Comment by ngoploti** [comment]
> You need to keep your `keystore` file and `keystore-passwords.properties` from your previous environment. This files are associated with Alfresco Repository and they are not related with mTLS but with Alfresco Repository encryption.
> 
> Discard the `keystore` and `keystore-passwords.properties` files generated by this project in `alfresco` folder and replace them by the existing in your previous environment.
Please do Alfresco Community Support encryption? If yes how to set it up?

I have this message in my Catalina.out file

 at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:478)
Caused by: org.alfresco.error.AlfrescoRuntimeException: 11230001 Failed to create key: metadata
 in key store:
   Location: /opt/tomcat/shared/classes/alfresco/extension/keystore/keystore
   Provider: null
   Type:     pkcs12
        at org.alfresco.encryption.AlfrescoKeyStoreImpl.createKey(AlfrescoKeyStoreImpl.java:664)
        at org.alfresco.encryption.AlfrescoKeyStoreImpl.validateKeys(AlfrescoKeyStoreImpl.java:915)
        at org.alfresco.encryption.AlfrescoKeyStoreImpl.validateKeys(AlfrescoKeyStoreImpl.java:188)
        at org.alfresco.encryption.KeyStoreChecker.validateKeyStores(KeyStoreChecker.java:49)
        at org.alfresco.encryption.EncryptionChecker$1.execute(EncryptionChecker.java:73)
        ... 57 more
Caused by: org.alfresco.error.AlfrescoRuntimeException: 11230000 Unable to get secret key: no key information is provided
        at org.alfresco.encryption.AlfrescoKeyStoreImpl.getSecretKey(AlfrescoKeyStoreImpl.java:775)
        at org.alfresco.encryption.AlfrescoKeyStoreImpl.createKey(AlfrescoKeyStoreImpl.java:642)
        ... 61 more
