### ISSUE TITLE
return status:403 when solr call alfresco

### ISSUE THREAD

**Issue by leencloud** [Alfresco/alfresco-ssl-generator#25]
Hello,

I'm trying to add mutual TLS authentication to ACS 7.1.

Keystores and truststores have been generated using the alfresco-ssl-generator tool:

```
./run.sh -keysize 2048 -alfrescoversion community -alfrescoformat classic -keystorepass "Leencloud" -truststorepass "Leencloud"
```

then start solr:
```
./solr/bin/solr start -a "-Dcreate.alfresco.defaults=alfresco,archive
-Dsolr.ssl.checkPeerName=false
-Dsolr.allow.unsafe.resourceloading=true
-Dssl-keystore.password=Leencloud
-Dssl-keystore.aliases=ssl-alfresco-ca,ssl-repo-client
-Dssl-keystore.ssl-alfresco-ca.password=Leencloud
-Dssl-keystore.ssl-repo-client.password=Leencloud
-Dssl-truststore.password=Leencloud
-Dssl-truststore.aliases=ssl-alfresco-ca,ssl-repo,ssl-repo-client
-Dssl-truststore.ssl-alfresco-ca.password=Leencloud
-Dssl-truststore.ssl-repo.password=Leencloud
-Dssl-truststore.ssl-repo-client.password=Leencloud" -f
```

then I got the 403 error in solr log:
```
2022-04-20 21:31:10.361 ERROR (org.alfresco.solr.AlfrescoCoreAdminHandler@a567e72_Worker-2) [   ] o.a.s.t.AbstractTracker [alfresco / ACL@1591121623 / IT #1650461470009] Tracking failure. See the stacktrace below for further details.
org.alfresco.error.AlfrescoRuntimeException: 03200000 api/solr/aclchangesets return status:403
	at org.alfresco.solr.client.SOLRAPIClient.callRepository(SOLRAPIClient.java:1596)
	at org.alfresco.solr.client.SOLRAPIClient.getAclChangeSets(SOLRAPIClient.java:185)
	at org.alfresco.solr.tracker.AclTracker.checkRepoAndIndexConsistency(AclTracker.java:416)
	at org.alfresco.solr.tracker.AclTracker.trackRepository(AclTracker.java:397)
	at org.alfresco.solr.tracker.AclTracker.doTrack(AclTracker.java:160)
	at org.alfresco.solr.tracker.AbstractTracker.track(AbstractTracker.java:242)
	at org.alfresco.solr.tracker.ActivatableTracker.track(ActivatableTracker.java:97)
	at org.alfresco.solr.tracker.TrackerJob.execute(TrackerJob.java:60)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
2022-04-20 21:31:10.361 ERROR (org.alfresco.solr.AlfrescoCoreAdminHandler@a567e72_Worker-3) [   ] o.a.s.t.AbstractTracker [archive / ACL@1504349981 / IT #1650461470009] Tracking failure. See the stacktrace below for further details.
org.alfresco.error.AlfrescoRuntimeException: 03200001 api/solr/aclchangesets return status:403
	at org.alfresco.solr.client.SOLRAPIClient.callRepository(SOLRAPIClient.java:1596)
	at org.alfresco.solr.client.SOLRAPIClient.getAclChangeSets(SOLRAPIClient.java:185)
	at org.alfresco.solr.tracker.AclTracker.checkRepoAndIndexConsistency(AclTracker.java:416)
	at org.alfresco.solr.tracker.AclTracker.trackRepository(AclTracker.java:397)
	at org.alfresco.solr.tracker.AclTracker.doTrack(AclTracker.java:160)
	at org.alfresco.solr.tracker.AbstractTracker.track(AbstractTracker.java:242)
	at org.alfresco.solr.tracker.ActivatableTracker.track(ActivatableTracker.java:97)
	at org.alfresco.solr.tracker.TrackerJob.execute(TrackerJob.java:60)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
2022-04-20 21:31:11.276 ERROR (ForkJoinPool-5-worker-7) [   ] o.a.s.SolrInformationServer Unable to update the text content of node 665. See the stacktrace below for further details.
org.alfresco.error.AlfrescoRuntimeException: 03200002 GetTextContentResponse return status is 403
	at org.alfresco.solr.client.SOLRAPIClient.getTextContent(SOLRAPIClient.java:1047)
	at org.alfresco.solr.SolrInformationServer.addContentPropertyToDocUsingAlfrescoRepository(SolrInformationServer.java:2741)
	at org.alfresco.solr.SolrInformationServer.addContentToDoc(SolrInformationServer.java:2701)
	at org.alfresco.solr.SolrInformationServer.updateContent(SolrInformationServer.java:1931)
	at org.alfresco.solr.tracker.ContentTracker$ContentIndexWorkerRunnable.doWork(ContentTracker.java:192)
	at org.alfresco.solr.tracker.AbstractWorker.run(AbstractWorker.java:48)
	at org.alfresco.solr.tracker.ContentTracker.lambda$doTrack$0(ContentTracker.java:131)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1654)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceTask.doLeaf(ReduceOps.java:952)
	at java.base/java.util.stream.ReduceOps$ReduceTask.doLeaf(ReduceOps.java:926)
	at java.base/java.util.stream.AbstractTask.compute(AbstractTask.java:327)
	at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:746)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
```

I noticed the content in alfresco-ssl-generator-master/ssl-tool/keystores/solr/ssl-truststore-passwords.properties:
```
aliases=alfresco.ca,ssl.repo,ssl.repo.client
keystore.password=Leencloud
alfresco.ca.password=Leencloud
ssl.repo.password=Leencloud
ssl.repo.client.password=Leencloud
```
The aliases is alfresco.ca, not ssl.alfresco.ca.
So I change the solr start command params to:
```
-Dssl-truststore.aliases=alfresco-ca,ssl-repo,ssl-repo-client
```

But got the same error.

**Comment by leencloud** [comment]
The connector setting in server.xml is:
```
<Connector port="8443" URIEncoding="UTF-8" protocol="HTTP/1.1"
      SSLEnabled="true" maxThreads="150" scheme="https"
      keystoreFile="/opt/alfresco-community/alf_data/keystore/ssl.keystore"
      keystorePass="Leencloud" keystoreType="JCEKS"
      secure="true" connectionTimeout="240000"
      truststoreFile="/opt/alfresco-community/alf_data/keystore/ssl.truststore"
      truststorePass="Leencloud" truststoreType="JCEKS"
      clientAuth="want" sslProtocol="TLS" allowUnsafeLegacyRenegotiation="true" maxHttpHeaderSize="32768" maxSavePostSize="-1" />
```

**Comment by aborroy** [comment]
Try using

```
-alfrescoformat current
```

**Comment by leencloud** [comment]
> Try using
> 
> ```
> -alfrescoformat current
> ```

I had tried using `-alfrescoformat current`, but got the same error.

alfresco-ssl-generator tool:
```
./run.sh -keysize 2048 -alfrescoversion community
```

alfresco-global.properties：
```
dir.root=/opt/alfresco-community/alf_data
dir.keystore=${ALF_DATA_DIR}/keystore

# encryption
solr.secureComms=https
# ssl encryption
encryption.ssl.keystore.location=${dir.keystore}/ssl.keystore
encryption.ssl.keystore.type=JCEKS
encryption.ssl.keystore.keyMetaData.location=
encryption.ssl.truststore.location=${dir.keystore}/ssl.truststore
encryption.ssl.truststore.type=JCEKS
encryption.ssl.truststore.keyMetaData.location=
# secret key keystore configuration
encryption.keystore.location=${dir.keystore}/keystore
encryption.keystore.keyMetaData.location=
encryption.keystore.type=JCEKS
solr.host=localhost
solr.port=8983
solr.port.ssl=8983
```

<TOMCAT_HOME>/conf/server.xml
```
 <Connector port="8443" protocol="HTTP/1.1"
     SSLEnabled="true" maxThreads="150" scheme="https"
     keystoreFile="/opt/alfresco-community/alf_data/keystore/ssl.keystore"
     keystorePass="keystore" keystoreType="JCEKS"
     secure="true" connectionTimeout="240000"
     truststoreFile="/opt/alfresco-community/alf_data/keystore/ssl.truststore"
     truststorePass="truststore" truststoreType="JCEKS"
     clientAuth="want" sslProtocol="TLS" />
```

<SOLR_HOME>/solrhome/templates/rerank/conf/solrcore.properties
```
alfresco.encryption.ssl.keystore.type=JCEKS
alfresco.encryption.ssl.keystore.location=ssl-repo-client.keystore
alfresco.encryption.ssl.keystore.passwordFileLocation=
alfresco.encryption.ssl.truststore.type=JCEKS
alfresco.encryption.ssl.truststore.location=ssl-repo-client.truststore
alfresco.encryption.ssl.truststore.passwordFileLocation=
```

alfresco-search-services/solr.in.sh：
```
SOLR_SSL_KEY_STORE=/opt/alfresco-community/alfresco-search-services/solrhome/keystore/ssl-repo-client.keystore
SOLR_SSL_KEY_STORE_PASSWORD=keystore
SOLR_SSL_KEY_STORE_TYPE=JCEKS
SOLR_SSL_TRUST_STORE=/opt/alfresco-community/alfresco-search-services/solrhome/keystore/ssl-repo-client.truststore
SOLR_SSL_TRUST_STORE_PASSWORD=truststore
SOLR_SSL_TRUST_STORE_TYPE=JCEKS
SOLR_SSL_NEED_CLIENT_AUTH=true
SOLR_SSL_WANT_CLIENT_AUTH=false
```

**Comment by aborroy** [comment]
You may check configuration is right, that 403 means that SOLR is not using https.

Hope this helps: https://github.com/aborroy/alfresco-mtls-tutorial
