### ISSUE TITLE
Java Environment Variables - please provide a working example

### ISSUE THREAD

**Issue by fpapiniTAI** [Alfresco/alfresco-ssl-generator#30]
Hi Angel, me... again.
"For the current format all the passwords are passed to the applications using Java Environment Variables, so the password files are not required any more."

I'm doing something wrong because I have defined absolutely nothing in alfresco-global.properties , I have this in setenv.sh :+1: 
[...]
JAVA_OPTS="$JAVA_OPTS \
    -Dencryption.keystore.type=JCEKS \
    -Dencryption.cipherAlgorithm=AES \
    -Dencryption.keyAlgorithm=AES \
    -Dencryption.keystore.location=/opt/alfresco/alf_data/keystore/keystore \
    -Dmetadata-keystore.password=password \
    -Dmetadata-keystore.aliases=metadata \
    -Dmetadata-keystore.metadata.password=password \
    -Dmetadata-keystore.metadata.algorithm=AES \
    -Ddir.keystore=/opt/alfresco/alf_data/keystore \
    -Dencryption.ssl.keystore.location=/opt/alfresco/alf_data/keystore/ssl.keystore \
    -Dencryption.ssl.keystore.type=JCEKS \
    -Dencryption.ssl.keystore.password=keystore \
    -Dencryption.ssl.keystore.metadata.password=keystore \
    -Dencryption.ssl.truststore.location=/opt/alfresco/alf_data/keystore/ssl.truststore \
    -Dencryption.ssl.truststore.type=JCEKS \
    -Dencryption.ssl.truststore.password=truststore" ;

but still I get a: "java.lang.IllegalArgumentException: password can't be null" so I guess my Java Environment Variables are not enough.

2022-11-18 21:15:00,010  ERROR [quartz.core.ErrorLogger] [SearchScheduler_Worker-4] Job (Solr.SolrWatcher threw an exception.
org.quartz.SchedulerException: Job threw an unhandled exception. [See nested exception: org.alfresco.error.AlfrescoRuntimeException: 10180362 Unable to create SSL context]
        at org.quartz.core.JobRunShell.run(JobRunShell.java:213)
        at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
Caused by: org.alfresco.error.AlfrescoRuntimeException: 10180362 Unable to create SSL context
        at org.alfresco.encryption.ssl.AuthSSLProtocolSocketFactory.getSSLContext(AuthSSLProtocolSocketFactory.java:130)
        at org.alfresco.encryption.ssl.AuthSSLProtocolSocketFactory.createSocket(AuthSSLProtocolSocketFactory.java:165)
        at org.apache.commons.httpclient.HttpConnection.open(HttpConnection.java:707)
        at org.apache.commons.httpclient.MultiThreadedHttpConnectionManager$HttpConnectionAdapter.open(MultiThreadedHttpConnectionManager.java:1361)
        at org.apache.commons.httpclient.HttpMethodDirector.executeWithRetry(HttpMethodDirector.java:387)
        at org.apache.commons.httpclient.HttpMethodDirector.executeMethod(HttpMethodDirector.java:171)
        at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:397)
        at org.alfresco.httpclient.RequestHeadersHttpClient.executeMethod(RequestHeadersHttpClient.java:84)
        at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:323)
        at org.alfresco.httpclient.RequestHeadersHttpClient.executeMethod(RequestHeadersHttpClient.java:69)
        at org.alfresco.repo.search.impl.solr.AbstractSolrAdminHTTPClient.getOperation(AbstractSolrAdminHTTPClient.java:73)
        at org.alfresco.repo.solr.SOLRAdminClient.executeAction(SOLRAdminClient.java:221)
        at org.alfresco.repo.solr.SOLRAdminClient$SolrTracker.pingSolr(SOLRAdminClient.java:333)
        at org.alfresco.repo.solr.SOLRWatcherJob.execute(SOLRWatcherJob.java:54)
        at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
        ... 1 more
Caused by: org.alfresco.error.AlfrescoRuntimeException: 10180361 Unable to create key manager
        at org.alfresco.encryption.AlfrescoKeyStoreImpl.createKeyManagers(AlfrescoKeyStoreImpl.java:337)
        at org.alfresco.encryption.ssl.AuthSSLProtocolSocketFactory.createSSLContext(AuthSSLProtocolSocketFactory.java:103)
        at org.alfresco.encryption.ssl.AuthSSLProtocolSocketFactory.getSSLContext(AuthSSLProtocolSocketFactory.java:124)
        ... 15 more
Caused by: java.lang.IllegalArgumentException: password can't be null
        at java.base/com.sun.crypto.provider.KeyProtector.<init>(KeyProtector.java:114)
        at java.base/com.sun.crypto.provider.JceKeyStore.engineGetKey(JceKeyStore.java:129)
        at java.base/java.security.KeyStore.getKey(KeyStore.java:1057)
        at java.base/sun.security.ssl.SunX509KeyManagerImpl.<init>(SunX509KeyManagerImpl.java:145)
        at java.base/sun.security.ssl.KeyManagerFactoryImpl$SunX509.engineInit(KeyManagerFactoryImpl.java:70)
        at java.base/javax.net.ssl.KeyManagerFactory.init(KeyManagerFactory.java:271)
        at org.alfresco.encryption.AlfrescoKeyStoreImpl.createKeyManagers(AlfrescoKeyStoreImpl.java:332)
        ... 17 more

Thanks for your valuable help!

**Comment by aborroy** [comment]
Is that configuration for Alfresco Repository or for Search Services?

You may find also useful to generate the mTLS configuration with https://github.com/alfresco/alfresco-docker-installer so you can identify required environment variables in Repo and Solr.

**Comment by fpapiniTAI** [comment]
Hi Angel,
your suggestion solved my problem, thanks again!
